# Generated by Django 4.2.2 on 2023-06-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='interest',
            new_name='data1',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='age',
            new_name='data2',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='data3',
        ),
    ]
