# Generated by Django 4.2.2 on 2023-06-13 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0002_rename_interest_person_data1_rename_age_person_data2_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Test',
        ),
    ]
