# Generated by Django 4.2.2 on 2023-06-20 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0003_rename_person_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('species', models.CharField(max_length=100)),
                ('reason_for_felling', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wood_grade', models.CharField(max_length=50)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumber.log')),
            ],
        ),
        migrations.CreateModel(
            name='MoistureCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumber.plank')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lumber.tree'),
        ),
    ]
