# Generated by Django 4.2.2 on 2023-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0004_log_tree_plank_moisturecheck_log_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
