# Generated by Django 4.2.2 on 2023-06-22 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0005_alter_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plank',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 6, 22)),
        ),
    ]
