# Generated by Django 4.2.2 on 2023-06-22 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0006_plank_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plank',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
