# Generated by Django 4.2.2 on 2023-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0007_alter_plank_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
