# Generated by Django 4.2.2 on 2023-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0008_test_latitude_test_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
    ]
