# Generated by Django 4.2.2 on 2023-06-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0009_alter_test_latitude_alter_test_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
    ]
