# Generated by Django 4.2.2 on 2023-06-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0010_alter_test_latitude_alter_test_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropboxTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dropbox_files/')),
            ],
        ),
    ]
