# Generated by Django 4.2.2 on 2023-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0011_dropboxtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxtest',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
