# Generated by Django 4.2.2 on 2023-06-26 10:16

from django.db import migrations, models
import storages.backends.dropbox


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0012_alter_dropboxtest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropboxtest',
            name='file',
            field=models.FileField(storage=storages.backends.dropbox.DropBoxStorage(), upload_to=''),
        ),
    ]
