# Generated by Django 4.2.2 on 2023-06-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0015_plank_live_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plank',
            name='furniture',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plank',
            name='general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plank',
            name='structural',
            field=models.BooleanField(default=False),
        ),
    ]
