# Generated by Django 4.2.2 on 2023-06-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0016_plank_furniture_plank_general_plank_structural'),
    ]

    operations = [
        migrations.AddField(
            model_name='plank',
            name='info',
            field=models.TextField(default='No extra information on this wood.'),
        ),
    ]
