# Generated by Django 4.2.2 on 2023-06-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0017_plank_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tree',
            name='lumberjack',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
