# Generated by Django 4.2.2 on 2023-06-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0018_tree_age_tree_latitude_tree_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='buck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='log',
            name='diameter',
            field=models.DecimalField(decimal_places=2, default=2.22, max_digits=5),
        ),
        migrations.AddField(
            model_name='plank',
            name='operator',
            field=models.CharField(default='Andrew Cargill', max_length=100),
        ),
    ]
