# Generated by Django 4.2.2 on 2023-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0019_log_buck_log_diameter_plank_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default_post_kg2mvg', upload_to='images/')),
            ],
        ),
    ]
