# Generated by Django 4.2.2 on 2023-06-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumber', '0020_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='plank',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tree',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
